### ISSUE TITLE
Clarification Needed on Which File to Execute

### ISSUE THREAD

**Issue by Lydia558** [AIMLAB-QuantumAI/Quantum_object_detection#12]
I am currently trying to run the code provided in this repository, but I am having difficulty determining which file I should execute to start the process. There are multiple files in the repository, and it is unclear which one serves as the entry point or main script for execution.

Could you please provide clear instructions on:
(1) Which file is intended to be executed as the main entry point?
(2) Any additional setup steps or commands required before running the code?

Having this information would greatly help in understanding the intended workflow and ensuring the code runs as expected. Thank you for your assistance!

**Comment by emilyjiminroh** [comment]
To run the code provided in this repository, you need to follow a few steps to set up the environment and execute the appropriate scripts for different purposes. First, refer to the **README** file for detailed instructions on downloading the required dataset. Ensure that you organize the files in your local environment according to the directory structure specified in the README, as the code relies on this hierarchy for proper execution.

For training the model, you should execute the **train_QCNN.py** script. This script serves as the entry point for initiating the training process. For evaluation of the model’s performance, use the **test_qcnn.py** script, which is designed to perform testing and generate evaluation metrics. If you want to extract or visualize demo videos, you can run the **qcnn_demo.py** script, which is specifically intended for generating demonstration outputs.

Before executing these scripts, make sure that all required dependencies mentioned in the README are installed in your environment. Using a virtual environment is recommended to prevent conflicts with existing packages. Additionally, verify that the dataset paths and configuration parameters in the scripts match your local setup. Following these steps will ensure that the code runs as intended and produces the desired results. If you encounter any challenges during setup or execution, feel free to seek further assistance.
