### ISSUE TITLE
Support for arbitary filter size

### ISSUE THREAD

**Issue by chmoon0314** [AIMLAB-QuantumAI/Quantum_object_detection#14]
- Does this version of repository supports the arbitrary filter size? Or do you have any plan to support it

**Comment by emilyjiminroh** [comment]
The current version supports a 2x2 QCNN model by default, but with the following code, it can extend support up to a 3x3 QCNN filter:
class QConv2d(tq.QuantumModule):  # 3x3 Quanvolution filter
    def __init__(self, in_channels=1, out_channels=10, kernel_size=3, stride=1,
                 n_wires=9, num_shot=256, tau=1, padding=0, bias=None):
        ...
        
This implementation allows users to specify the desired filter size and adjust it accordingly. If you plan to implement support for arbitrary filter sizes, the approach would involve making the kernel size and related parameters more dynamically configurable in the constructor and ensuring compatibility in the quantum circuit design.
